-- OntologyStore DB lookup tables
-- Demo project
INSERT INTO CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','/Demo/','ontstore','i2b2demodata','java:/OntologyStoreDataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
INSERT INTO ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','Demo/','ontstore','i2b2metadata','java:/OntologyStoreMetadataDS','ORACLE','Metadata',CURRENT_TIMESTAMP);
-- ACT project
INSERT INTO CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','/ACT/','ontstore','i2b2demodata','java:/OntologyStoreACTDataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
INSERT INTO ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','ACT/','ontstore','i2b2actata','java:/OntologyStoreACTMetadataDS','ORACLE','Metadata',CURRENT_TIMESTAMP);
