CREATE INDEX META_FULLNAME_IDX_i2b2 ON I2B2(C_FULLNAME);
CREATE INDEX META_APPLIED_PATH_IDX_i2b2 ON I2B2(M_APPLIED_PATH);
CREATE INDEX META_EXCLUSION_IDX_i2b2 ON I2B2(M_EXCLUSION_CD);
CREATE INDEX META_HLEVEL_IDX_i2b2 ON I2B2(C_HLEVEL);
CREATE INDEX META_SYNONYM_IDX_i2b2 ON I2B2(C_SYNONYM_CD);