//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.22 at 02:07:56 AM EDT 
//


package edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Terminologies_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "terminologies");
    private final static QName _Product_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "product");
    private final static QName _Products_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "products");
    private final static QName _ProductActions_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "product_actions");
    private final static QName _ActionSummaries_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "action_summaries");
    private final static QName _ActionSummary_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "action_summary");
    private final static QName _ProductAction_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "product_action");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TerminologiesType }
     * 
     */
    public TerminologiesType createTerminologiesType() {
        return new TerminologiesType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ProductActionsType }
     * 
     */
    public ProductActionsType createProductActionsType() {
        return new ProductActionsType();
    }

    /**
     * Create an instance of {@link ActionSummariesType }
     * 
     */
    public ActionSummariesType createActionSummariesType() {
        return new ActionSummariesType();
    }

    /**
     * Create an instance of {@link ActionSummaryType }
     * 
     */
    public ActionSummaryType createActionSummaryType() {
        return new ActionSummaryType();
    }

    /**
     * Create an instance of {@link ProductActionType }
     * 
     */
    public ProductActionType createProductActionType() {
        return new ProductActionType();
    }

    /**
     * Create an instance of {@link ProductsType }
     * 
     */
    public ProductsType createProductsType() {
        return new ProductsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminologiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "terminologies")
    public JAXBElement<TerminologiesType> createTerminologies(TerminologiesType value) {
        return new JAXBElement<TerminologiesType>(_Terminologies_QNAME, TerminologiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "product")
    public JAXBElement<ProductType> createProduct(ProductType value) {
        return new JAXBElement<ProductType>(_Product_QNAME, ProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "products")
    public JAXBElement<ProductsType> createProducts(ProductsType value) {
        return new JAXBElement<ProductsType>(_Products_QNAME, ProductsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductActionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "product_actions")
    public JAXBElement<ProductActionsType> createProductActions(ProductActionsType value) {
        return new JAXBElement<ProductActionsType>(_ProductActions_QNAME, ProductActionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionSummariesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "action_summaries")
    public JAXBElement<ActionSummariesType> createActionSummaries(ActionSummariesType value) {
        return new JAXBElement<ActionSummariesType>(_ActionSummaries_QNAME, ActionSummariesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionSummaryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "action_summary")
    public JAXBElement<ActionSummaryType> createActionSummary(ActionSummaryType value) {
        return new JAXBElement<ActionSummaryType>(_ActionSummary_QNAME, ActionSummaryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductActionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "product_action")
    public JAXBElement<ProductActionType> createProductAction(ProductActionType value) {
        return new JAXBElement<ProductActionType>(_ProductAction_QNAME, ProductActionType.class, null, value);
    }

}
