//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.22 at 02:07:56 AM EDT 
//


package edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="include_network_package" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="download" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="install" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productActionType", propOrder = {
    "title",
    "key",
    "includeNetworkPackage",
    "download",
    "install"
})
public class ProductActionType {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String key;
    @XmlElement(name = "include_network_package", defaultValue = "false")
    protected boolean includeNetworkPackage;
    @XmlElement(defaultValue = "false")
    protected boolean download;
    @XmlElement(defaultValue = "false")
    protected boolean install;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the includeNetworkPackage property.
     * 
     */
    public boolean isIncludeNetworkPackage() {
        return includeNetworkPackage;
    }

    /**
     * Sets the value of the includeNetworkPackage property.
     * 
     */
    public void setIncludeNetworkPackage(boolean value) {
        this.includeNetworkPackage = value;
    }

    /**
     * Gets the value of the download property.
     * 
     */
    public boolean isDownload() {
        return download;
    }

    /**
     * Sets the value of the download property.
     * 
     */
    public void setDownload(boolean value) {
        this.download = value;
    }

    /**
     * Gets the value of the install property.
     * 
     */
    public boolean isInstall() {
        return install;
    }

    /**
     * Sets the value of the install property.
     * 
     */
    public void setInstall(boolean value) {
        this.install = value;
    }

}
