//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.10.12 at 03:57:54 PM EDT
//
package edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName PRODUCT_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "product");
    private final static QName PRODUCTS_QNAME = new QName("http://www.i2b2.org/xsd/cell/ontologystore/1.1/", "products");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo
     *
     */
    public ObjectFactory() {
    }

    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "product")
    public JAXBElement<ProductType> createProduct(ProductType value) {
        return new JAXBElement<>(PRODUCT_QNAME, ProductType.class, null, value);
    }

    @XmlElementDecl(namespace = "http://www.i2b2.org/xsd/cell/ontologystore/1.1/", name = "products")
    public JAXBElement<ProductsType> createProducts(ProductsType value) {
        return new JAXBElement<>(PRODUCTS_QNAME, ProductsType.class, null, value);
    }

}
