//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.22 at 02:07:56 AM EDT 
//


package edu.pitt.dbmi.i2b2.ontologystore.datavo.vdo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="file_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="terminologies" type="{http://www.i2b2.org/xsd/cell/ontologystore/1.1/}terminologiesType"/>
 *         &lt;element name="include_network_package" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="downloaded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="installed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="failed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productType", propOrder = {
    "fileName",
    "title",
    "version",
    "owner",
    "type",
    "terminologies",
    "includeNetworkPackage",
    "downloaded",
    "installed",
    "started",
    "failed"
})
public class ProductType {

    @XmlElement(name = "file_name", required = true)
    protected String fileName;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(required = true)
    protected String owner;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected TerminologiesType terminologies;
    @XmlElement(name = "include_network_package", defaultValue = "false")
    protected boolean includeNetworkPackage;
    @XmlElement(defaultValue = "false")
    protected boolean downloaded;
    @XmlElement(defaultValue = "false")
    protected boolean installed;
    @XmlElement(defaultValue = "false")
    protected boolean started;
    @XmlElement(defaultValue = "false")
    protected boolean failed;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the terminologies property.
     * 
     * @return
     *     possible object is
     *     {@link TerminologiesType }
     *     
     */
    public TerminologiesType getTerminologies() {
        return terminologies;
    }

    /**
     * Sets the value of the terminologies property.
     * 
     * @param value
     *     allowed object is
     *     {@link TerminologiesType }
     *     
     */
    public void setTerminologies(TerminologiesType value) {
        this.terminologies = value;
    }

    /**
     * Gets the value of the includeNetworkPackage property.
     * 
     */
    public boolean isIncludeNetworkPackage() {
        return includeNetworkPackage;
    }

    /**
     * Sets the value of the includeNetworkPackage property.
     * 
     */
    public void setIncludeNetworkPackage(boolean value) {
        this.includeNetworkPackage = value;
    }

    /**
     * Gets the value of the downloaded property.
     * 
     */
    public boolean isDownloaded() {
        return downloaded;
    }

    /**
     * Sets the value of the downloaded property.
     * 
     */
    public void setDownloaded(boolean value) {
        this.downloaded = value;
    }

    /**
     * Gets the value of the installed property.
     * 
     */
    public boolean isInstalled() {
        return installed;
    }

    /**
     * Sets the value of the installed property.
     * 
     */
    public void setInstalled(boolean value) {
        this.installed = value;
    }

    /**
     * Gets the value of the started property.
     * 
     */
    public boolean isStarted() {
        return started;
    }

    /**
     * Sets the value of the started property.
     * 
     */
    public void setStarted(boolean value) {
        this.started = value;
    }

    /**
     * Gets the value of the failed property.
     * 
     */
    public boolean isFailed() {
        return failed;
    }

    /**
     * Sets the value of the failed property.
     * 
     */
    public void setFailed(boolean value) {
        this.failed = value;
    }

}
