CREATE TABLE I2B2 (
  CONCEPT_PATH VARCHAR2(700) NOT NULL,
  CONCEPT_CD VARCHAR2(50) NULL,
  NAME_CHAR VARCHAR2(2000) NULL,
  CONCEPT_BLOB CLOB NULL,
  UPDATE_DATE DATE NULL,
  DOWNLOAD_DATE DATE NULL,
  IMPORT_DATE DATE NULL,
  SOURCESYSTEM_CD VARCHAR2(50) NULL,
  UPLOAD_ID NUMBER(38,0) NULL,
  CONSTRAINT I2B2_PK PRIMARY KEY(CONCEPT_PATH)
)