DROP SCHEMA i2b2actdx_ont CASCADE;
DROP SCHEMA i2b2actpcori_ont CASCADE;
DROP SCHEMA i2b2actomp_ont CASCADE;
DROP SCHEMA i2b2actdx_crc CASCADE;
DROP SCHEMA i2b2actpcori_crc CASCADE;
DROP SCHEMA i2b2actomp_crc CASCADE;
