CREATE TABLE IF NOT EXISTS schematable (
  CONCEPT_PATH VARCHAR(700) NOT NULL,
  CONCEPT_CD VARCHAR(50) NULL,
  NAME_CHAR VARCHAR(2000) NULL,
  CONCEPT_BLOB TEXT NULL,
  UPDATE_DATE TIMESTAMP NULL,
  DOWNLOAD_DATE TIMESTAMP NULL,
  IMPORT_DATE TIMESTAMP NULL,
  SOURCESYSTEM_CD VARCHAR(50) NULL,
  UPLOAD_ID INT NULL,
  CONSTRAINT tableindex_PK PRIMARY KEY(CONCEPT_PATH)
)