CREATE TABLE i2b2actata.dbo.SCHEMES (
	C_KEY varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_DESCRIPTION varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT ACT_SCHEMES_PK PRIMARY KEY (C_KEY)
);

CREATE TABLE i2b2actata.dbo.TABLE_ACCESS (
	C_TABLE_CD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_TABLE_NAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_PROTECTED_ACCESS char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C_ONTOLOGY_PROTECTION varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C_HLEVEL int NOT NULL,
	C_FULLNAME varchar(700) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_NAME varchar(2000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_SYNONYM_CD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_VISUALATTRIBUTES char(3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_TOTALNUM int NULL,
	C_BASECODE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C_METADATAXML varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C_FACTTABLECOLUMN varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_DIMTABLENAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_COLUMNNAME varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_COLUMNDATATYPE varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_OPERATOR varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_DIMCODE varchar(700) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	C_COMMENT varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C_TOOLTIP varchar(900) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	C_ENTRY_DATE datetime NULL,
	C_CHANGE_DATE datetime NULL,
	C_STATUS_CD char(1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VALUETYPE_CD varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

