
INSERT INTO i2b2pm.dbo.PM_CELL_DATA (CELL_ID,PROJECT_PATH,NAME,METHOD_CD,URL,CAN_OVERRIDE,ENTRY_DATE,STATUS_CD) VALUES ('ONTSTORE','/','OntologyStore Cell','REST','http://localhost:9090/i2b2/services/OntologyStoreService/',1,CURRENT_TIMESTAMP,'A');

INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','i2b2','ONTSTORE_ADMIN',CURRENT_TIMESTAMP,'A');