-- create i2b2 user
INSERT INTO i2b2pm.dbo.PM_USER_DATA (USER_ID,FULL_NAME,PASSWORD,ENTRY_DATE,STATUS_CD) VALUES ('kvb2','Kevin Bui','9117d59a69dc49807671a51f10ab7f',current_timestamp,'A');

-- add user to Demo project
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_AGG',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_DEID',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_LDS',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_OBFSC',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_PROT',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','EDITOR',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','USER',current_timestamp,'A');

-- add user to ACT project
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_AGG',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_DEID',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_LDS',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_OBFSC',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_PROT',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','EDITOR',current_timestamp,'A');
INSERT INTO i2b2pm.dbo.PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','USER',current_timestamp,'A');
