CREATE TABLE schematable (
  CONCEPT_PATH VARCHAR(700) NOT NULL,
  CONCEPT_CD VARCHAR(50) NULL,
  NAME_CHAR VARCHAR(2000) NULL,
  CONCEPT_BLOB VARCHAR(MAX) NULL,
  UPDATE_DATE DATETIME NULL,
  DOWNLOAD_DATE DATETIME NULL,
  IMPORT_DATE DATETIME NULL,
  SOURCESYSTEM_CD VARCHAR(50) NULL,
  UPLOAD_ID INT NULL,
  CONSTRAINT tableindex_PK PRIMARY KEY(CONCEPT_PATH)
)