-- add user to ACT project
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','USER',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','DATA_DEID',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','DATA_OBFSC',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','DATA_AGG',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','DATA_LDS',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','EDITOR',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','demo','DATA_PROT',CURRENT_TIMESTAMP,'A');
