CREATE INDEX META_FULLNAME_IDX_tableindex ON schematable(C_FULLNAME);
CREATE INDEX META_APPLIED_PATH_IDX_tableindex ON schematable(M_APPLIED_PATH);
CREATE INDEX META_EXCLUSION_IDX_tableindex ON schematable(M_EXCLUSION_CD);
CREATE INDEX META_HLEVEL_IDX_tableindex ON schematable(C_HLEVEL);
CREATE INDEX META_SYNONYM_IDX_tableindex ON schematable(C_SYNONYM_CD);