-- create i2b2 user
INSERT INTO PM_USER_DATA (USER_ID,FULL_NAME,PASSWORD,ENTRY_DATE,STATUS_CD) VALUES ('kvb2','Kevin Bui','9117d59a69dc49807671a51f10ab7f',CURRENT_TIMESTAMP,'A');

-- add user to Demo project
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','USER',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_DEID',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_OBFSC',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_AGG',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_LDS',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','EDITOR',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('Demo','kvb2','DATA_PROT',CURRENT_TIMESTAMP,'A');

-- add user to ACT project
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','USER',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_DEID',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_OBFSC',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_AGG',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_LDS',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','EDITOR',CURRENT_TIMESTAMP,'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,ENTRY_DATE,STATUS_CD) VALUES ('ACT','kvb2','DATA_PROT',CURRENT_TIMESTAMP,'A');
