-- update ACT ontology datasource path
UPDATE I2B2HIVE.ONT_DB_LOOKUP SET C_DB_FULLSCHEMA = 'i2b2actata' WHERE C_PROJECT_PATH = 'ACT/';

-- OntologyStore settings
INSERT INTO I2B2HIVE.HIVE_CELL_PARAMS (ID,DATATYPE_CD,CELL_ID,PARAM_NAME_CD,VALUE,STATUS_CD) VALUES ((SELECT MAX(id)+1 FROM I2B2HIVE.HIVE_CELL_PARAMS),'T','ONTSTORE','ontstore.product.list.url',TO_CLOB('http://localhost/~kvb2/s3/ontology-store-v2/product-list-local-all.json'),'A');
INSERT INTO I2B2HIVE.HIVE_CELL_PARAMS (ID,DATATYPE_CD,CELL_ID,PARAM_NAME_CD,VALUE,STATUS_CD) VALUES ((SELECT MAX(id)+1 FROM I2B2HIVE.HIVE_CELL_PARAMS),'T','ONTSTORE','ontstore.dir.download',TO_CLOB('/home/kvb2/shared/ontology/products-v2'),'A');

-- ontologystore ds
INSERT INTO I2B2HIVE.CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME) VALUES ('i2b2demo','/Demo/','ontstore','i2b2demodata','java:/OntologyStoreDataDS','ORACLE','Demo');
INSERT INTO I2B2HIVE.ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME) VALUES ('i2b2demo','Demo/','ontstore','i2b2ontstoremetadata','java:/OntologyStoreMetadataDS','ORACLE','Demo');
-- ACT ontologystore ds
INSERT INTO I2B2HIVE.CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME) VALUES ('i2b2demo','/ACT/','ontstore','i2b2demodata','java:/OntologyStoreACTDataDS','ORACLE','Demo');
INSERT INTO I2B2HIVE.ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME) VALUES ('i2b2demo','ACT/','ontstore','i2b2ontstoremetadata','java:/OntologyStoreACTMetadataDS','ORACLE','Demo');
