CREATE TABLE I2B2ACTATA.SCHEMES (
	C_KEY VARCHAR2(50),
	C_NAME VARCHAR2(50),
	C_DESCRIPTION VARCHAR2(100),
	CONSTRAINT ACT_SCHEMES_PK PRIMARY KEY (C_KEY)
);

CREATE TABLE I2B2ACTATA.TABLE_ACCESS (
    "C_TABLE_CD" VARCHAR2(50) NOT NULL ENABLE, 
    "C_TABLE_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "C_PROTECTED_ACCESS" CHAR(1), 
    "C_ONTOLOGY_PROTECTION" CLOB, 
    "C_HLEVEL" NUMBER(22,0) NOT NULL ENABLE, 
    "C_FULLNAME" VARCHAR2(700) NOT NULL ENABLE, 
    "C_NAME" VARCHAR2(2000) NOT NULL ENABLE, 
    "C_SYNONYM_CD" CHAR(1) NOT NULL ENABLE, 
    "C_VISUALATTRIBUTES" CHAR(3) NOT NULL ENABLE, 
    "C_TOTALNUM" NUMBER(22,0), 
    "C_BASECODE" VARCHAR2(50), 
    "C_METADATAXML" CLOB, 
    "C_FACTTABLECOLUMN" VARCHAR2(50) NOT NULL ENABLE, 
    "C_DIMTABLENAME" VARCHAR2(50) NOT NULL ENABLE, 
    "C_COLUMNNAME" VARCHAR2(50) NOT NULL ENABLE, 
    "C_COLUMNDATATYPE" VARCHAR2(50) NOT NULL ENABLE, 
    "C_OPERATOR" VARCHAR2(10) NOT NULL ENABLE, 
    "C_DIMCODE" VARCHAR2(700) NOT NULL ENABLE, 
    "C_COMMENT" CLOB, 
    "C_TOOLTIP" VARCHAR2(900), 
    "C_ENTRY_DATE" DATE, 
    "C_CHANGE_DATE" DATE, 
    "C_STATUS_CD" CHAR(1), 
    "VALUETYPE_CD" VARCHAR2(50)
);

CREATE TABLE I2B2ACTATA.QT_BREAKDOWN_PATH (
    "NAME" VARCHAR2(100), 
    "VALUE" CLOB, 
    "CREATE_DATE" DATE, 
    "UPDATE_DATE" DATE, 
    "USER_ID" VARCHAR2(50), 
    "GROUP_ID" VARCHAR2(50)
);
