-- OntologyStore settings
INSERT INTO I2B2HIVE.HIVE_CELL_PARAMS (ID,DATATYPE_CD,CELL_ID,PARAM_NAME_CD,VALUE,ENTRY_DATE,STATUS_CD) VALUES ((SELECT MAX(id)+1 FROM I2B2HIVE.HIVE_CELL_PARAMS),'T','ONTSTORE','ontstore.product.list.url',TO_CLOB('http://localhost/~kvb2/s3/ontology-store-v2/product-list-local-all.json'),CURRENT_TIMESTAMP,'A');
INSERT INTO I2B2HIVE.HIVE_CELL_PARAMS (ID,DATATYPE_CD,CELL_ID,PARAM_NAME_CD,VALUE,ENTRY_DATE,STATUS_CD) VALUES ((SELECT MAX(id)+1 FROM I2B2HIVE.HIVE_CELL_PARAMS),'T','ONTSTORE','ontstore.dir.download',TO_CLOB('/home/kvb2/shared/ontology/products-v2'),CURRENT_TIMESTAMP,'A');

-- ontologystore ds
-- INSERT INTO I2B2HIVE.CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','/Demo/','ontstore','i2b2demodata','java:/OntologyStoreDataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
-- INSERT INTO I2B2HIVE.ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','Demo/','ontstore','i2b2metadata','java:/OntologyStoreMetadataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
-- ACT ontologystore ds
-- INSERT INTO I2B2HIVE.CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','/ACT/','ontstore','i2b2demodata','java:/OntologyStoreACTDataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
-- INSERT INTO I2B2HIVE.ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','ACT/','ontstore','i2b2actata','java:/OntologyStoreACTMetadataDS','ORACLE','Demo',CURRENT_TIMESTAMP);

-- ontologystore ds on ACT project
INSERT INTO I2B2HIVE.CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','/Demo/','ontstore','i2b2demodata','java:/OntologyStoreDataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
INSERT INTO I2B2HIVE.ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','Demo/','ontstore','i2b2metadata','java:/OntologyStoreMetadataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
INSERT INTO I2B2HIVE.CRC_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','/ACT/','ontstore','i2b2demodata','java:/OntologyStoreDataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
INSERT INTO I2B2HIVE.ONT_DB_LOOKUP (C_DOMAIN_ID,C_PROJECT_PATH,C_OWNER_ID,C_DB_FULLSCHEMA,C_DB_DATASOURCE,C_DB_SERVERTYPE,C_DB_NICENAME,C_ENTRY_DATE) VALUES ('i2b2demo','ACT/','ontstore','i2b2actata','java:/OntologyStoreMetadataDS','ORACLE','Demo',CURRENT_TIMESTAMP);
