-- create i2b2 user
INSERT INTO PM_USER_DATA (USER_ID,FULL_NAME,PASSWORD,STATUS_CD) VALUES ('kvb2','Kevin Bui','9117d59a69dc49807671a51f10ab7f','A');

-- add user to Demo project
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','USER','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','DATA_DEID','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','DATA_OBFSC','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','DATA_AGG','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','DATA_LDS','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','EDITOR','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('Demo','kvb2','DATA_PROT','A');

-- add user to ACT project
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','USER','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','DATA_DEID','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','DATA_OBFSC','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','DATA_AGG','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','DATA_LDS','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','EDITOR','A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID,USER_ID,USER_ROLE_CD,STATUS_CD) VALUES ('ACT','kvb2','DATA_PROT','A');
