//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.12 at 03:57:54 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i2b2.org/xsd/hive/msg/1.1/")
package edu.pitt.dbmi.i2b2.ontologystore.datavo.i2b2message;
